bundle open actionpack

    def unwrapped_exception
      puts "in unwrapped exception"
      if wrapper_exceptions.include?(exception.class.to_s)
        puts "outer exception is exceptional, unwrap"
        exception.cause
      else
        puts "provide outer exception"
        exception
      end
    end

RuntimeError (What status code?):
  
app/controllers/foos_controller.rb:12:in `raise_not_found'
in unwrapped exception
provide outer exception

bundle pristine
